export const HOME_PAGE = "/"
export const ANIMALS_PAGE = "/mascotas"
export const PET_DETAILS_PAGE = "/mascotas/:id"
export const LOGIN_PAGE = "/iniciar-sesion"
export const EMERGENCY_FORM_PAGE = "/formulario-emergencia"
export const FAQ_PAGE = "/preguntas-frecuentes"
export const BLOG_PAGE = "/blog"
export const CALENDAR_PAGE = "/calendario"
